<?php

namespace AppShed\Extensions\StorageBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiRepository extends EntityRepository
{
}
